$(function(){
	$("#spxq").hide();
	$("#sp").hover(function(){
		$("#spxq").show(500);
	},function(){
		$("#spxq").hide(300);
	})
	$(".qy").hide();
	$("#qy").hover(function(){
		$(".qy").show(500);
	},function(){
		$(".qy").hide(300);
	})
	$(".qd").hide();
	$("#qd").hover(function(){
		$(".qd").show(500);
	},function(){
		$(".qd").hide(300);
	})
})